version: 2

project_name: chatgpt2api

builds:
  - id: chatgpt2api
    main: ./internal
    binary: chatgpt2api
    flags:
      - -tags=embed
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X chatgpt2api/internal/version.Version={{ .Version }}
      - -X chatgpt2api/internal/version.Commit={{ .Commit }}
      - -X chatgpt2api/internal/version.Date={{ .Date }}
      - -X chatgpt2api/internal/version.BuildType=release
      - -X chatgpt2api/internal/version.DefaultUpdateRepo={{ .Env.GITHUB_REPO_OWNER }}/{{ .Env.GITHUB_REPO_NAME }}

archives:
  - id: default
    formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

changelog:
  disable: true

release:
  draft: false
  prerelease: auto
  replace_existing_artifacts: true
  name_template: "chatgpt2api {{ .Version }}"
  header: |
    {{ .Env.TAG_MESSAGE }}
